project:
  type: website
  output-dir: docs

website:
  title: "Marine Ecosystem Dynamics - 2025"
  navbar:
    right:
      - text: MATERIAL
        href: MATERIAL/index.qmd
      - icon: "github"
        href: "https://github.com/KMGJan"
        target: "_blank"
      - icon: envelope
        href: mailto:kinlan.jan@su.se
  page-footer:
    border: false
    left: "![](/assets/images/SU_black.svg){height=2.5em style=margin-bottom:-1px;}"
    center: "Marine Ecosystem Dynamics 2025 | [Athena](https://athena.itslearning.com/){target=_blank}"
    right: "Published with [Quarto](https://quarto.org/){target=_blank}"
format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true
    self-contained: true
knitr:
  opts_chunk:
    echo: true
    collapse: true
    comment: "#>"
    fig.align: "center"


